### ISSUE TITLE
Fresh install 'npm run dev'

### ISSUE THREAD

**Issue by awcodes** [laravel-frontend-presets/tall#39]
Just tried a fresh install with the present and am encountering the following error upon 'npm run dev'

Never encountered this before. I have installed the preset several times successfully.

Any help would be greatly appreciated. :)

Seems like it might be a webpack issue. Not sure.

Error: Package exports for '/Users/[redacted]/Dev/DisclosuresReader/node_modules/kleur' do not define a valid './colors' target 

full error:
Error: Package exports for '/Users/[redacted]/Dev/DisclosuresReader/node_modules/kleur' do not define a valid './colors' target 
at resolveExportsTarget (internal/modules/cjs/loader.js:607:9)
    at applyExports (internal/modules/cjs/loader.js:492:14)
    at resolveExports (internal/modules/cjs/loader.js:541:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:643:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:941:27)
    at Function.Module._load (internal/modules/cjs/loader.js:847:27)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (/Users/[redacted]/Dev/DisclosuresReader/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/[redacted]/Dev/DisclosuresReader/node_modules/autoprefixer/lib/autoprefixer.js:9:13)
    at Module._compile (/Users/[redacted]/Dev/DisclosuresReader/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (/Users/[redacted]/Dev/DisclosuresReader/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at /Users/[redacted]/Dev/DisclosuresReader/node_modules/laravel-mix/src/components/Preprocessor.js:62:41
    at /Users/[redacted]/Dev/DisclosuresReader/node_modules/laravel-mix/src/components/Preprocessor.js:69:31
    at global.tap (/Users/[redacted]/Dev/DisclosuresReader/node_modules/laravel-mix/src/helpers.js:10:5)
    at /Users/[redacted]/Dev/DisclosuresReader/node_modules/laravel-mix/src/components/Preprocessor.js:27:13
    at Array.forEach (<anonymous>)
    at Sass.webpackRules (/Users/[redacted]/Dev/DisclosuresReader/node_modules/laravel-mix/src/components/Preprocessor.js:22:22)
    at ComponentFactory.applyRules (/Users/[redacted]/Dev/DisclosuresReader/node_modules/laravel-mix/src/components/ComponentFactory.js:155:23)
    at /Users/[redacted]/Dev/DisclosuresReader/node_modules/laravel-mix/src/components/ComponentFactory.js:66:48
    at /Users/[redacted]/Dev/DisclosuresReader/node_modules/laravel-mix/src/Dispatcher.js:34:47
    at Array.forEach (<anonymous>)
    at Dispatcher.fire (/Users/[redacted]/Dev/DisclosuresReader/node_modules/laravel-mix/src/Dispatcher.js:34:28)
    at Mix.dispatch (/Users/[redacted]/Dev/DisclosuresReader/node_modules/laravel-mix/src/Mix.js:118:25)
    at WebpackConfig.buildRules (/Users/[redacted]/Dev/DisclosuresReader/node_modules/laravel-mix/src/builder/WebpackConfig.js:90:13)
    at WebpackConfig.build (/Users/[redacted]/Dev/DisclosuresReader/node_modules/laravel-mix/src/builder/WebpackConfig.js:23:14)
    at Object.<anonymous> (/Users/[redacted]/Dev/DisclosuresReader/node_modules/laravel-mix/setup/webpack.config.js:29:38)
    at Module._compile (/Users/[redacted]/Dev/DisclosuresReader/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (/Users/[redacted]/Dev/DisclosuresReader/node_modules/v8-compile-cache/v8-compile-cache.js:161:20) {
  code: 'MODULE_NOT_FOUND'

**Comment by PatrickJoannisse** [comment]
Had the same issue. Updating Node did the trick.

https://github.com/lukeed/kleur/issues/32

**Comment by DanHarrin** [comment]
Thanks, @PatrickJoannisse!
